# Twitter keys and tokens.
ACCESS_TOKEN = '2895194074-aOob3Vm4JouYMWIf4ITdhNB0DeNtVb4ZP4MhDLX'
ACCESS_TOKEN_SECRET = 'C1LvXWDLIcwGooTewzVlRQbZuPTlTWKWvMmX6b9ZuNMUn'
CONSUMER_KEY = 'UFj1LutyO64ggZiKesMHNDosd'
CONSUMER_KEY_SECRET = 'Jd9FqfeMZXb2snT3IGHiMKzwh79JZkoqUbBBGeKuc0jiYfJUHu'

def getKeys():
    return (ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_KEY_SECRET)
